apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meureplcaset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: anapassos/conversao-temperatura:latest
        ports:
        - containerPort: 8080

